version: '3'

services:
  rabbitmq:
    image: bitnami/rabbitmq:3.8.9
    environment:
      RABBITMQ_USERNAME: user
      RABBITMQ_PASSWORD: pass
    ports:
      - 5672:5672
      - 15672:15672
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"

