spring:
  application:
    name: Workflow Search

server:
  port : 8082

elastic:
  host: localhost
  port: 9200
  workflowIndex: workflow
  taskIndex: task

service-info:
  authInstructionsUrl: "https://example.com/auth"
  contactInfoUrl: "https://example.com/contact"
  defaultWorkflowEngineParameters:
    - defaultValue:
      name: "defaultContainer"
      type: "type 1"
    - defaultValue:
      name: "workflowVersion"
      type: "type 2"
  supportedFilesystemProtocols:
    - "S3"
    - "SCORE"
  supportedWesVersions:
    - "1.0.0"
  workflowType: "nextflow"
  workflowEngineVersions:
    nextflow: "19.10.0"
  workflowTypeVersions:
    nextflow-dna-seq-alignment: "0.0.1"

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphql.playground:
  enabled: true
  cdn:
    enabled: false