spring:
  application:
    name: "Workflow Search"
    version: ^project.version^
    description: "Workflow Search API Documentation"

server:
  port : 8089

elastic:
  host: localhost
  port: 9200
  useHttps: false
  useAuthentication: false
  username: elastic
  password: testing
  workflowIndex: workflow
  taskIndex: task

service-info:
  authInstructionsUrl: "https://example.com/auth"
  contactInfoUrl: "mailto:dcc-support@icgc.org"
  supportedFilesystemProtocols:
    - "None"
  supportedWesVersions:
    - "1.0.0"
  workflowType: "nextflow"
  workflowEngineVersions:
    nextflow: "20.07.1"
  workflowTypeVersions:
    any-nextflow-workflow: "X.X.X"
  defaultWorkflowEngineParameters:
    - defaultValue:
      name: "NA"
      type: "NA"

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
  playground:
    enabled: true
    cdn:
      enabled: false

---
spring.profiles: secure
auth:
  jwtPublicKeyStr: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0lOqMuPLCVusc6szklNXQL1FHhSkEgR7An+8BllBqTsRHM4bRYosseGFCbYPn8r8FsWuMDtxp0CwTyMQR2PCbJ740DdpbE1KC6jAfZxqcBete7gP0tooJtbvnA6X4vNpG4ukhtUoN9DzNOO0eqMU0Rgyy5HjERdYEWkwTNB30i9I+nHFOSj4MGLBSxNlnuo3keeomCRgtimCx+L/K3HNo0QHTG1J7RzLVAchfQT0lu3pUJ8kB+UM6/6NG+fVyysJyRZ9gadsr4gvHHckw8oUBp2tHvqBEkEdY+rt1Mf5jppt7JUV7HAPLB/qR5jhALY2FX/8MN+lPLmb/nLQQichVQIDAQAB\n-----END PUBLIC KEY-----"
  graphqlScopes:
    queryOnly:
      - RDPC-CA.READ
    queryAndMutation:
      - RDPC-CA.WRITE
