spring:
  application:
    name: "Workflow API"
    version: ^project.version^
    description: "Workflow API"
  data:
    elasticsearch:
      client:
        reactive:
          max-in-memory-size: -1

server:
  port : 8080

elastic:
  host: localhost
  port: 9200
  useHttps: false
  useAuthentication: false
  username: elastic
  password: testing
  workflowIndex: workflow
  taskIndex: task

service-info:
  authInstructionsUrl: "https://example.com/auth"
  contactInfoUrl: "mailto:dcc-support@icgc.org"
  supportedFilesystemProtocols:
    - "None"
  supportedWesVersions:
    - "1.0.0"
  workflowType: "nextflow"
  workflowEngineVersions:
    nextflow: "20.07.1"
  workflowTypeVersions:
    any-nextflow-workflow: "X.X.X"
  defaultWorkflowEngineParameters:
    - defaultValue:
      name: "NA"
      type: "NA"

---
spring.config.activate.on-profile: secure
auth:
  jwtPublicKeyUrl: "http://localhost:8081/oauth/token/public_key"
  jwtPublicKeyStr: "-----BEGIN PUBLIC KEY-----\nSET ME IF YOU DONT HAVE A URL, BUT URL TAKES PRIORITY\n-----END PUBLIC KEY-----"
  graphqlScopes:
    queryOnly:
      - RDPC-DEV.READ
    queryAndMutation:
      - RDPC-DEV.WRITE

---
rabbit:
  default-endpoint-name: standalone
  endpoints:
    standalone:
      host: localhost
      port: 5672
      username: user
      password: pass

api.producer:
  topicExchange: "gatekeeper-in"
  initializeRunReq: false

logging:
  level:
    org:
      icgc:
        argo: DEBUG