spring:
  application:
    name: "Workflow Search"
    version: ^project.version^
    description: "Workflow Search API Documentation"

server:
  port : 8088

elastic:
  host: workflow-es.rdpc-qa.cancercollaboratory.org
  port: 443
  useHttps: true
  useAuthentication: true
  username: elastic
  password: h5bdgjfh4gdqhkdcjdj5hj59
  workflowIndex: workflow
  taskIndex: task

#elastic:
#  host: localhost
#  port: 9200
#  useHttps: false
#  useAuthentication: true
#  username: elastic
#  password: magicword
#  workflowIndex: workflow
#  taskIndex: task

service-info:
  authInstructionsUrl: "https://example.com/auth"
  contactInfoUrl: "mailto:dcc-support@icgc.org"
  supportedFilesystemProtocols:
    - "None"
  supportedWesVersions:
    - "1.0.0"
  workflowType: "nextflow"
  workflowEngineVersions:
    nextflow: "20.07.1"
  workflowTypeVersions:
    any-nextflow-workflow: "X.X.X"
  defaultWorkflowEngineParameters:
    - defaultValue:
      name: "NA"
      type: "NA"

---
spring.profiles: secure
auth:
  jwtPublicKeyUrl: "https://ego.qa.argo.cancercollaboratory.org/api/oauth/token/public_key"
#  jwtPublicKeyStr: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnzyis1ZjfNB0bBgKFMSvvkTtwlvBsaJq7S5wA+kzeVOVpVWwkWdVha4s38XM/pa/yr47av7+z3VTmvDRyAHcaT92whREFpLv9cj5lTeJSibyr/Mrm/YtjCZVWgaOYIhwrXwKLqPr/11inWsAkfIytvHWTxZYEcXLgAXFuUuaS3uF9gEiNQwzGTU1v0FqkqTBr4B8nW3HCN47XUu0t8Y0e+lf4s4OxQawWD79J9/5d3Ry0vbV3Am1FtGJiJvOwRsIfVChDpYStTcHTCMqtvWbV6L11BWkpzGXSW4Hv43qa+GSYOD2QU68Mb59oSk2OB+BtOLpJofmbGEGgvmwyCI9MwIDAQAB\n-----END PUBLIC KEY-----"
  graphqlScopes:
    queryOnly:
      - RDPC-CA.READ
    queryAndMutation:
      - RDPC-CA.WRITE

logging.level:
  org.icgc_argo.workflow.search: DEBUG
