/**
 * Autogenerated by Avro
 *
 * <p>DO NOT EDIT DIRECTLY
 */
package org.icgc_argo.workflow.search.rabbitmq.schema;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class WfMgmtRunMsg extends org.apache.avro.specific.SpecificRecordBase
    implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6059246197616722454L;
  public static final org.apache.avro.Schema SCHEMA$ =
      new org.apache.avro.Schema.Parser()
          .parse(
              "{\"type\":\"record\",\"name\":\"WfMgmtRunMsg\",\"namespace\":\"org.icgc_argo.workflow.search.rabbitmq.schema\",\"fields\":[{\"name\":\"timestamp\",\"type\":\"long\",\"logicalType\":\"date\"},{\"name\":\"runId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"state\",\"type\":{\"type\":\"enum\",\"name\":\"RunState\",\"symbols\":[\"UNKNOWN\",\"QUEUED\",\"INITIALIZING\",\"RUNNING\",\"PAUSED\",\"CANCELING\",\"CANCELED\",\"COMPLETE\",\"EXECUTOR_ERROR\",\"SYSTEM_ERROR\"]}},{\"name\":\"workflowUrl\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"workflowType\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"workflowTypeVersion\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"workflowParamsJsonStr\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"workflowEngineParams\",\"type\":{\"type\":\"record\",\"name\":\"EngineParams\",\"fields\":[{\"name\":\"defaultContainer\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"revision\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"launchDir\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"projectDir\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"workDir\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"latest\",\"type\":[\"null\",\"boolean\"],\"default\":null},{\"name\":\"resume\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}}]}");

  public static org.apache.avro.Schema getClassSchema() {
    return SCHEMA$;
  }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<WfMgmtRunMsg> ENCODER =
      new BinaryMessageEncoder<WfMgmtRunMsg>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<WfMgmtRunMsg> DECODER =
      new BinaryMessageDecoder<WfMgmtRunMsg>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   *
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<WfMgmtRunMsg> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   *
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<WfMgmtRunMsg> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link
   * SchemaStore}.
   *
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<WfMgmtRunMsg> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<WfMgmtRunMsg>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this WfMgmtRunMsg to a ByteBuffer.
   *
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a WfMgmtRunMsg from a ByteBuffer.
   *
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a WfMgmtRunMsg instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of
   *     this class
   */
  public static WfMgmtRunMsg fromByteBuffer(java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long timestamp;
  private java.lang.String runId;
  private org.icgc_argo.workflow.search.rabbitmq.schema.RunState state;
  private java.lang.String workflowUrl;
  private java.lang.String workflowType;
  private java.lang.String workflowTypeVersion;
  private java.lang.String workflowParamsJsonStr;
  private org.icgc_argo.workflow.search.rabbitmq.schema.EngineParams workflowEngineParams;

  /**
   * Default constructor. Note that this does not initialize fields to their default values from the
   * schema. If that is desired then one should use <code>newBuilder()</code>.
   */
  public WfMgmtRunMsg() {}

  /**
   * All-args constructor.
   *
   * @param timestamp The new value for timestamp
   * @param runId The new value for runId
   * @param state The new value for state
   * @param workflowUrl The new value for workflowUrl
   * @param workflowType The new value for workflowType
   * @param workflowTypeVersion The new value for workflowTypeVersion
   * @param workflowParamsJsonStr The new value for workflowParamsJsonStr
   * @param workflowEngineParams The new value for workflowEngineParams
   */
  public WfMgmtRunMsg(
      java.lang.Long timestamp,
      java.lang.String runId,
      org.icgc_argo.workflow.search.rabbitmq.schema.RunState state,
      java.lang.String workflowUrl,
      java.lang.String workflowType,
      java.lang.String workflowTypeVersion,
      java.lang.String workflowParamsJsonStr,
      org.icgc_argo.workflow.search.rabbitmq.schema.EngineParams workflowEngineParams) {
    this.timestamp = timestamp;
    this.runId = runId;
    this.state = state;
    this.workflowUrl = workflowUrl;
    this.workflowType = workflowType;
    this.workflowTypeVersion = workflowTypeVersion;
    this.workflowParamsJsonStr = workflowParamsJsonStr;
    this.workflowEngineParams = workflowEngineParams;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() {
    return MODEL$;
  }

  public org.apache.avro.Schema getSchema() {
    return SCHEMA$;
  }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
      case 0:
        return timestamp;
      case 1:
        return runId;
      case 2:
        return state;
      case 3:
        return workflowUrl;
      case 4:
        return workflowType;
      case 5:
        return workflowTypeVersion;
      case 6:
        return workflowParamsJsonStr;
      case 7:
        return workflowEngineParams;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value = "unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
      case 0:
        timestamp = (java.lang.Long) value$;
        break;
      case 1:
        runId = value$ != null ? value$.toString() : null;
        break;
      case 2:
        state = (org.icgc_argo.workflow.search.rabbitmq.schema.RunState) value$;
        break;
      case 3:
        workflowUrl = value$ != null ? value$.toString() : null;
        break;
      case 4:
        workflowType = value$ != null ? value$.toString() : null;
        break;
      case 5:
        workflowTypeVersion = value$ != null ? value$.toString() : null;
        break;
      case 6:
        workflowParamsJsonStr = value$ != null ? value$.toString() : null;
        break;
      case 7:
        workflowEngineParams = (org.icgc_argo.workflow.search.rabbitmq.schema.EngineParams) value$;
        break;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'timestamp' field.
   *
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   *
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'runId' field.
   *
   * @return The value of the 'runId' field.
   */
  public java.lang.String getRunId() {
    return runId;
  }

  /**
   * Sets the value of the 'runId' field.
   *
   * @param value the value to set.
   */
  public void setRunId(java.lang.String value) {
    this.runId = value;
  }

  /**
   * Gets the value of the 'state' field.
   *
   * @return The value of the 'state' field.
   */
  public org.icgc_argo.workflow.search.rabbitmq.schema.RunState getState() {
    return state;
  }

  /**
   * Sets the value of the 'state' field.
   *
   * @param value the value to set.
   */
  public void setState(org.icgc_argo.workflow.search.rabbitmq.schema.RunState value) {
    this.state = value;
  }

  /**
   * Gets the value of the 'workflowUrl' field.
   *
   * @return The value of the 'workflowUrl' field.
   */
  public java.lang.String getWorkflowUrl() {
    return workflowUrl;
  }

  /**
   * Sets the value of the 'workflowUrl' field.
   *
   * @param value the value to set.
   */
  public void setWorkflowUrl(java.lang.String value) {
    this.workflowUrl = value;
  }

  /**
   * Gets the value of the 'workflowType' field.
   *
   * @return The value of the 'workflowType' field.
   */
  public java.lang.String getWorkflowType() {
    return workflowType;
  }

  /**
   * Sets the value of the 'workflowType' field.
   *
   * @param value the value to set.
   */
  public void setWorkflowType(java.lang.String value) {
    this.workflowType = value;
  }

  /**
   * Gets the value of the 'workflowTypeVersion' field.
   *
   * @return The value of the 'workflowTypeVersion' field.
   */
  public java.lang.String getWorkflowTypeVersion() {
    return workflowTypeVersion;
  }

  /**
   * Sets the value of the 'workflowTypeVersion' field.
   *
   * @param value the value to set.
   */
  public void setWorkflowTypeVersion(java.lang.String value) {
    this.workflowTypeVersion = value;
  }

  /**
   * Gets the value of the 'workflowParamsJsonStr' field.
   *
   * @return The value of the 'workflowParamsJsonStr' field.
   */
  public java.lang.String getWorkflowParamsJsonStr() {
    return workflowParamsJsonStr;
  }

  /**
   * Sets the value of the 'workflowParamsJsonStr' field.
   *
   * @param value the value to set.
   */
  public void setWorkflowParamsJsonStr(java.lang.String value) {
    this.workflowParamsJsonStr = value;
  }

  /**
   * Gets the value of the 'workflowEngineParams' field.
   *
   * @return The value of the 'workflowEngineParams' field.
   */
  public org.icgc_argo.workflow.search.rabbitmq.schema.EngineParams getWorkflowEngineParams() {
    return workflowEngineParams;
  }

  /**
   * Sets the value of the 'workflowEngineParams' field.
   *
   * @param value the value to set.
   */
  public void setWorkflowEngineParams(
      org.icgc_argo.workflow.search.rabbitmq.schema.EngineParams value) {
    this.workflowEngineParams = value;
  }

  /**
   * Creates a new WfMgmtRunMsg RecordBuilder.
   *
   * @return A new WfMgmtRunMsg RecordBuilder
   */
  public static org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder newBuilder() {
    return new org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder();
  }

  /**
   * Creates a new WfMgmtRunMsg RecordBuilder by copying an existing Builder.
   *
   * @param other The existing builder to copy.
   * @return A new WfMgmtRunMsg RecordBuilder
   */
  public static org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder newBuilder(
      org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder other) {
    if (other == null) {
      return new org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder();
    } else {
      return new org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder(other);
    }
  }

  /**
   * Creates a new WfMgmtRunMsg RecordBuilder by copying an existing WfMgmtRunMsg instance.
   *
   * @param other The existing instance to copy.
   * @return A new WfMgmtRunMsg RecordBuilder
   */
  public static org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder newBuilder(
      org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg other) {
    if (other == null) {
      return new org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder();
    } else {
      return new org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder(other);
    }
  }

  /** RecordBuilder for WfMgmtRunMsg instances. */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder
      extends org.apache.avro.specific.SpecificRecordBuilderBase<WfMgmtRunMsg>
      implements org.apache.avro.data.RecordBuilder<WfMgmtRunMsg> {

    private long timestamp;
    private java.lang.String runId;
    private org.icgc_argo.workflow.search.rabbitmq.schema.RunState state;
    private java.lang.String workflowUrl;
    private java.lang.String workflowType;
    private java.lang.String workflowTypeVersion;
    private java.lang.String workflowParamsJsonStr;
    private org.icgc_argo.workflow.search.rabbitmq.schema.EngineParams workflowEngineParams;
    private org.icgc_argo.workflow.search.rabbitmq.schema.EngineParams.Builder
        workflowEngineParamsBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     *
     * @param other The existing Builder to copy.
     */
    private Builder(org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[0].schema(), other.timestamp);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.runId)) {
        this.runId = data().deepCopy(fields()[1].schema(), other.runId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.state)) {
        this.state = data().deepCopy(fields()[2].schema(), other.state);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.workflowUrl)) {
        this.workflowUrl = data().deepCopy(fields()[3].schema(), other.workflowUrl);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.workflowType)) {
        this.workflowType = data().deepCopy(fields()[4].schema(), other.workflowType);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.workflowTypeVersion)) {
        this.workflowTypeVersion = data().deepCopy(fields()[5].schema(), other.workflowTypeVersion);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.workflowParamsJsonStr)) {
        this.workflowParamsJsonStr =
            data().deepCopy(fields()[6].schema(), other.workflowParamsJsonStr);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.workflowEngineParams)) {
        this.workflowEngineParams =
            data().deepCopy(fields()[7].schema(), other.workflowEngineParams);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (other.hasWorkflowEngineParamsBuilder()) {
        this.workflowEngineParamsBuilder =
            org.icgc_argo.workflow.search.rabbitmq.schema.EngineParams.newBuilder(
                other.getWorkflowEngineParamsBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing WfMgmtRunMsg instance
     *
     * @param other The existing instance to copy.
     */
    private Builder(org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[0].schema(), other.timestamp);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.runId)) {
        this.runId = data().deepCopy(fields()[1].schema(), other.runId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.state)) {
        this.state = data().deepCopy(fields()[2].schema(), other.state);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.workflowUrl)) {
        this.workflowUrl = data().deepCopy(fields()[3].schema(), other.workflowUrl);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.workflowType)) {
        this.workflowType = data().deepCopy(fields()[4].schema(), other.workflowType);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.workflowTypeVersion)) {
        this.workflowTypeVersion = data().deepCopy(fields()[5].schema(), other.workflowTypeVersion);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.workflowParamsJsonStr)) {
        this.workflowParamsJsonStr =
            data().deepCopy(fields()[6].schema(), other.workflowParamsJsonStr);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.workflowEngineParams)) {
        this.workflowEngineParams =
            data().deepCopy(fields()[7].schema(), other.workflowEngineParams);
        fieldSetFlags()[7] = true;
      }
      this.workflowEngineParamsBuilder = null;
    }

    /**
     * Gets the value of the 'timestamp' field.
     *
     * @return The value.
     */
    public long getTimestamp() {
      return timestamp;
    }

    /**
     * Sets the value of the 'timestamp' field.
     *
     * @param value The value of 'timestamp'.
     * @return This builder.
     */
    public org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder setTimestamp(
        long value) {
      validate(fields()[0], value);
      this.timestamp = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
     * Checks whether the 'timestamp' field has been set.
     *
     * @return True if the 'timestamp' field has been set, false otherwise.
     */
    public boolean hasTimestamp() {
      return fieldSetFlags()[0];
    }

    /**
     * Clears the value of the 'timestamp' field.
     *
     * @return This builder.
     */
    public org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder clearTimestamp() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
     * Gets the value of the 'runId' field.
     *
     * @return The value.
     */
    public java.lang.String getRunId() {
      return runId;
    }

    /**
     * Sets the value of the 'runId' field.
     *
     * @param value The value of 'runId'.
     * @return This builder.
     */
    public org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder setRunId(
        java.lang.String value) {
      validate(fields()[1], value);
      this.runId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
     * Checks whether the 'runId' field has been set.
     *
     * @return True if the 'runId' field has been set, false otherwise.
     */
    public boolean hasRunId() {
      return fieldSetFlags()[1];
    }

    /**
     * Clears the value of the 'runId' field.
     *
     * @return This builder.
     */
    public org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder clearRunId() {
      runId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
     * Gets the value of the 'state' field.
     *
     * @return The value.
     */
    public org.icgc_argo.workflow.search.rabbitmq.schema.RunState getState() {
      return state;
    }

    /**
     * Sets the value of the 'state' field.
     *
     * @param value The value of 'state'.
     * @return This builder.
     */
    public org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder setState(
        org.icgc_argo.workflow.search.rabbitmq.schema.RunState value) {
      validate(fields()[2], value);
      this.state = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
     * Checks whether the 'state' field has been set.
     *
     * @return True if the 'state' field has been set, false otherwise.
     */
    public boolean hasState() {
      return fieldSetFlags()[2];
    }

    /**
     * Clears the value of the 'state' field.
     *
     * @return This builder.
     */
    public org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder clearState() {
      state = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
     * Gets the value of the 'workflowUrl' field.
     *
     * @return The value.
     */
    public java.lang.String getWorkflowUrl() {
      return workflowUrl;
    }

    /**
     * Sets the value of the 'workflowUrl' field.
     *
     * @param value The value of 'workflowUrl'.
     * @return This builder.
     */
    public org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder setWorkflowUrl(
        java.lang.String value) {
      validate(fields()[3], value);
      this.workflowUrl = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
     * Checks whether the 'workflowUrl' field has been set.
     *
     * @return True if the 'workflowUrl' field has been set, false otherwise.
     */
    public boolean hasWorkflowUrl() {
      return fieldSetFlags()[3];
    }

    /**
     * Clears the value of the 'workflowUrl' field.
     *
     * @return This builder.
     */
    public org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder clearWorkflowUrl() {
      workflowUrl = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
     * Gets the value of the 'workflowType' field.
     *
     * @return The value.
     */
    public java.lang.String getWorkflowType() {
      return workflowType;
    }

    /**
     * Sets the value of the 'workflowType' field.
     *
     * @param value The value of 'workflowType'.
     * @return This builder.
     */
    public org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder setWorkflowType(
        java.lang.String value) {
      validate(fields()[4], value);
      this.workflowType = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
     * Checks whether the 'workflowType' field has been set.
     *
     * @return True if the 'workflowType' field has been set, false otherwise.
     */
    public boolean hasWorkflowType() {
      return fieldSetFlags()[4];
    }

    /**
     * Clears the value of the 'workflowType' field.
     *
     * @return This builder.
     */
    public org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder clearWorkflowType() {
      workflowType = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
     * Gets the value of the 'workflowTypeVersion' field.
     *
     * @return The value.
     */
    public java.lang.String getWorkflowTypeVersion() {
      return workflowTypeVersion;
    }

    /**
     * Sets the value of the 'workflowTypeVersion' field.
     *
     * @param value The value of 'workflowTypeVersion'.
     * @return This builder.
     */
    public org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder
        setWorkflowTypeVersion(java.lang.String value) {
      validate(fields()[5], value);
      this.workflowTypeVersion = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
     * Checks whether the 'workflowTypeVersion' field has been set.
     *
     * @return True if the 'workflowTypeVersion' field has been set, false otherwise.
     */
    public boolean hasWorkflowTypeVersion() {
      return fieldSetFlags()[5];
    }

    /**
     * Clears the value of the 'workflowTypeVersion' field.
     *
     * @return This builder.
     */
    public org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder
        clearWorkflowTypeVersion() {
      workflowTypeVersion = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
     * Gets the value of the 'workflowParamsJsonStr' field.
     *
     * @return The value.
     */
    public java.lang.String getWorkflowParamsJsonStr() {
      return workflowParamsJsonStr;
    }

    /**
     * Sets the value of the 'workflowParamsJsonStr' field.
     *
     * @param value The value of 'workflowParamsJsonStr'.
     * @return This builder.
     */
    public org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder
        setWorkflowParamsJsonStr(java.lang.String value) {
      validate(fields()[6], value);
      this.workflowParamsJsonStr = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
     * Checks whether the 'workflowParamsJsonStr' field has been set.
     *
     * @return True if the 'workflowParamsJsonStr' field has been set, false otherwise.
     */
    public boolean hasWorkflowParamsJsonStr() {
      return fieldSetFlags()[6];
    }

    /**
     * Clears the value of the 'workflowParamsJsonStr' field.
     *
     * @return This builder.
     */
    public org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder
        clearWorkflowParamsJsonStr() {
      workflowParamsJsonStr = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
     * Gets the value of the 'workflowEngineParams' field.
     *
     * @return The value.
     */
    public org.icgc_argo.workflow.search.rabbitmq.schema.EngineParams getWorkflowEngineParams() {
      return workflowEngineParams;
    }

    /**
     * Sets the value of the 'workflowEngineParams' field.
     *
     * @param value The value of 'workflowEngineParams'.
     * @return This builder.
     */
    public org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder
        setWorkflowEngineParams(org.icgc_argo.workflow.search.rabbitmq.schema.EngineParams value) {
      validate(fields()[7], value);
      this.workflowEngineParamsBuilder = null;
      this.workflowEngineParams = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
     * Checks whether the 'workflowEngineParams' field has been set.
     *
     * @return True if the 'workflowEngineParams' field has been set, false otherwise.
     */
    public boolean hasWorkflowEngineParams() {
      return fieldSetFlags()[7];
    }

    /**
     * Gets the Builder instance for the 'workflowEngineParams' field and creates one if it doesn't
     * exist yet.
     *
     * @return This builder.
     */
    public org.icgc_argo.workflow.search.rabbitmq.schema.EngineParams.Builder
        getWorkflowEngineParamsBuilder() {
      if (workflowEngineParamsBuilder == null) {
        if (hasWorkflowEngineParams()) {
          setWorkflowEngineParamsBuilder(
              org.icgc_argo.workflow.search.rabbitmq.schema.EngineParams.newBuilder(
                  workflowEngineParams));
        } else {
          setWorkflowEngineParamsBuilder(
              org.icgc_argo.workflow.search.rabbitmq.schema.EngineParams.newBuilder());
        }
      }
      return workflowEngineParamsBuilder;
    }

    /**
     * Sets the Builder instance for the 'workflowEngineParams' field
     *
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder
        setWorkflowEngineParamsBuilder(
            org.icgc_argo.workflow.search.rabbitmq.schema.EngineParams.Builder value) {
      clearWorkflowEngineParams();
      workflowEngineParamsBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'workflowEngineParams' field has an active Builder instance
     *
     * @return True if the 'workflowEngineParams' field has an active Builder instance
     */
    public boolean hasWorkflowEngineParamsBuilder() {
      return workflowEngineParamsBuilder != null;
    }

    /**
     * Clears the value of the 'workflowEngineParams' field.
     *
     * @return This builder.
     */
    public org.icgc_argo.workflow.search.rabbitmq.schema.WfMgmtRunMsg.Builder
        clearWorkflowEngineParams() {
      workflowEngineParams = null;
      workflowEngineParamsBuilder = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public WfMgmtRunMsg build() {
      try {
        WfMgmtRunMsg record = new WfMgmtRunMsg();
        record.timestamp =
            fieldSetFlags()[0] ? this.timestamp : (java.lang.Long) defaultValue(fields()[0]);
        record.runId =
            fieldSetFlags()[1] ? this.runId : (java.lang.String) defaultValue(fields()[1]);
        record.state =
            fieldSetFlags()[2]
                ? this.state
                : (org.icgc_argo.workflow.search.rabbitmq.schema.RunState)
                    defaultValue(fields()[2]);
        record.workflowUrl =
            fieldSetFlags()[3] ? this.workflowUrl : (java.lang.String) defaultValue(fields()[3]);
        record.workflowType =
            fieldSetFlags()[4] ? this.workflowType : (java.lang.String) defaultValue(fields()[4]);
        record.workflowTypeVersion =
            fieldSetFlags()[5]
                ? this.workflowTypeVersion
                : (java.lang.String) defaultValue(fields()[5]);
        record.workflowParamsJsonStr =
            fieldSetFlags()[6]
                ? this.workflowParamsJsonStr
                : (java.lang.String) defaultValue(fields()[6]);
        if (workflowEngineParamsBuilder != null) {
          try {
            record.workflowEngineParams = this.workflowEngineParamsBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("workflowEngineParams"));
            throw e;
          }
        } else {
          record.workflowEngineParams =
              fieldSetFlags()[7]
                  ? this.workflowEngineParams
                  : (org.icgc_argo.workflow.search.rabbitmq.schema.EngineParams)
                      defaultValue(fields()[7]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<WfMgmtRunMsg> WRITER$ =
      (org.apache.avro.io.DatumWriter<WfMgmtRunMsg>) MODEL$.createDatumWriter(SCHEMA$);

  @Override
  public void writeExternal(java.io.ObjectOutput out) throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<WfMgmtRunMsg> READER$ =
      (org.apache.avro.io.DatumReader<WfMgmtRunMsg>) MODEL$.createDatumReader(SCHEMA$);

  @Override
  public void readExternal(java.io.ObjectInput in) throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override
  protected boolean hasCustomCoders() {
    return true;
  }

  @Override
  public void customEncode(org.apache.avro.io.Encoder out) throws java.io.IOException {
    out.writeLong(this.timestamp);

    out.writeString(this.runId);

    out.writeEnum(this.state.ordinal());

    if (this.workflowUrl == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.workflowUrl);
    }

    if (this.workflowType == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.workflowType);
    }

    if (this.workflowTypeVersion == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.workflowTypeVersion);
    }

    if (this.workflowParamsJsonStr == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.workflowParamsJsonStr);
    }

    this.workflowEngineParams.customEncode(out);
  }

  @Override
  public void customDecode(org.apache.avro.io.ResolvingDecoder in) throws java.io.IOException {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.timestamp = in.readLong();

      this.runId = in.readString();

      this.state = org.icgc_argo.workflow.search.rabbitmq.schema.RunState.values()[in.readEnum()];

      if (in.readIndex() != 1) {
        in.readNull();
        this.workflowUrl = null;
      } else {
        this.workflowUrl = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.workflowType = null;
      } else {
        this.workflowType = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.workflowTypeVersion = null;
      } else {
        this.workflowTypeVersion = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.workflowParamsJsonStr = null;
      } else {
        this.workflowParamsJsonStr = in.readString();
      }

      if (this.workflowEngineParams == null) {
        this.workflowEngineParams =
            new org.icgc_argo.workflow.search.rabbitmq.schema.EngineParams();
      }
      this.workflowEngineParams.customDecode(in);

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
          case 0:
            this.timestamp = in.readLong();
            break;

          case 1:
            this.runId = in.readString();
            break;

          case 2:
            this.state =
                org.icgc_argo.workflow.search.rabbitmq.schema.RunState.values()[in.readEnum()];
            break;

          case 3:
            if (in.readIndex() != 1) {
              in.readNull();
              this.workflowUrl = null;
            } else {
              this.workflowUrl = in.readString();
            }
            break;

          case 4:
            if (in.readIndex() != 1) {
              in.readNull();
              this.workflowType = null;
            } else {
              this.workflowType = in.readString();
            }
            break;

          case 5:
            if (in.readIndex() != 1) {
              in.readNull();
              this.workflowTypeVersion = null;
            } else {
              this.workflowTypeVersion = in.readString();
            }
            break;

          case 6:
            if (in.readIndex() != 1) {
              in.readNull();
              this.workflowParamsJsonStr = null;
            } else {
              this.workflowParamsJsonStr = in.readString();
            }
            break;

          case 7:
            if (this.workflowEngineParams == null) {
              this.workflowEngineParams =
                  new org.icgc_argo.workflow.search.rabbitmq.schema.EngineParams();
            }
            this.workflowEngineParams.customDecode(in);
            break;

          default:
            throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}
